### ISSUE TITLE
analog sensor read crashes spark core

### ISSUE THREAD

**Issue by michaeldewayneharris** [voodootikigod/voodoospark#23]
I discovered a bug that is related to voodoospark when using cylonjs.  I believe this is a problem with voodoospark and not cylonjs.

if you build this circuit http://docs.spark.io/assets/images/breadboard-temp-sensor.jpg and run this code http://pastebin.com/9acm0AjY.

The default tinker firmware will run the application fine.  

if you update to voodoospark firmware the sparkcore will not return proper values for the temperature reading, and shortly red light the core and it will crash the hardware and restart ending the application.

**Comment by rwaldron** [comment]
This has been fixed for some time
