### ISSUE TITLE
Problem while accessing arduino core libraries in Ardupilot code??

### ISSUE THREAD

**Issue by anisjamil** [voodootikigod/voodoospark#41]
Hello,

I'm using "ArduPilot-Arduino-1.0.3-windows" which has been modified for Ardupilot code. In this version of the compiler arduino core libraries are deliberately excluded.

I want to use some functions like pinMode(), digitalWrite() etc., but due to the exclusion of these libraries I'm unable to use these functions in my code.

Can some one PLEASE help me out how to use these functions?? I'm totally stuck on this point. I have used arduino IDE 1.0.6 and many other versions which were downloaded from Arduino's official Website which access to these functions but do not execute the code.

Thank You in advance...........

**Comment by rwaldron** [comment]
This is a general purpose, thin client IO layer, not meant to be an application layer itself, therefore does not need application layer libraries.
